### ISSUE TITLE
set up continuous integration pathway

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-services#22]
- [x] install docker/eris
- [x] move repo to ~/.eris/services
- [x] start / stop all services (eris services should have assurances they'll at least start without erroring)
- [ ] add all to eris ipfs gateway
- [ ] update toadserver (for now)
- [ ] update libsChain (later)

**Comment by zramsay** [comment]
to update the toadserver, we can give a priv key to circle as env var, and write that to a file that gets used to sign the tx. i think that'll work

**Comment by zramsay** [comment]
currently just a mock test but all the pieces are in place to turn this on, which will happen when toadserver in production
