### ISSUE TITLE
deprecate repo

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-services#55]
- [x] remove third party service definition files & Dockerfiles
- [x] keep anything ops related for cli but move to `/hello-eris/dockerfiles`
- [ ] have cli generate service definition files using go templates (like cm does it)

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1003](https://github.com/eris-ltd/eris-cli/issues/1003) via [**ZenHub**](https://www.zenhub.com/)
