### ISSUE TITLE
update/revise definition files

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-services#9]
- standardize what's included in commented lines
- add link to Dockerfile that built the image
- add link to services spec / explain some fields. 
- [location] repo = "repo of the service" -> rather than repo of this repo

Basically, assume less about the reader of this file (who might also be wanting to build a service).

**Comment by compleatang** [comment]
think we should combine bullets 2 and 4.... 

[location] -> linkToDockerfile

is probably the best

**Comment by zramsay** [comment]
:+1:
